### ISSUE TITLE
Plugin not working for W10

### ISSUE THREAD

**Issue by michaelwalgraeve** [litehelpers/Cordova-sqlite-legacy#2]
I am using this plugin for an application which runs on iOS/Android/W10.
Version v 0.7.17 worked fine but with the latest update:

When executing the "openDatabase" command it keeps crashing on 

`var db = new SQLite3JS.Database(opendbname);` (in sqlite-proxy.js)

I don't know how to debug deeper. 
iOS runs with the new iOSdatabaselocation parameter. 
Android works like before.

**Comment by brodybits** [comment]
Can you try a small test program?

Can you also give cordova-sqlite-ext a try?

**Comment by michaelwalgraeve** [comment]
Nothing wrong with your code. I've done an update of Apple/Parallels/Windows and Visual Studio with Cordova. It works now.
