### ISSUE TITLE
Unable to run example code on Cordova WP8

### ISSUE THREAD

**Issue by sumitsoman** [litehelpers/Cordova-sqlite-legacy#4]
I am unable to use the Cordova SQLite plugin with my WP8 application. The example is not working. The following is the JS code

    window.sqlitePlugin.openDatabase({ name: 'hello-world.db', location: 'default' }, function (db) {
    db.executeSql("select length('tenletters') as stringlength", [], function (res) {
       var stringlength = res.rows.item(0).stringlength;
      alert('got stringlength: ' + stringlength);
      });
    });

The following error is shown in the console:

> Unable to get property 'openDatabase' of undefined or null reference. Source File: x-wmapp0:www/js/CreateTableScript.js, Line: 2 Unable to get property 'querySelector' of undefined or null reference. Source File: x-wmapp0:www/js/index.js, Line: 41
> How to fix this? The WP8 project has been created using Cordova v6.2.0.

**Comment by brodybits** [comment]
Please post a Cordova project that demonstrates this issue and I can look at it later this week.

**Comment by sumitsoman** [comment]
The project is attached.

[sqlitetest.zip](https://github.com/litehelpers/Cordova-sqlite-legacy/files/289406/sqlitetest.zip)

**Comment by sumitsoman** [comment]
Hi, have you had a chance to look at this? I've not yet been able to resolve!

**Comment by sumitsoman** [comment]
Please help, I have been unable to resolve this issue yet.

**Comment by brodybits** [comment]
My apologies. I am fighting a very tight deadline for a client and can look at this after the next 1-2 weeks.

**Comment by brodybits** [comment]
@sumitsoman your code uses an alert to confirm that it is working. Unfortunately alert does not seem to work on Windows or WP8 platforms.

I suggest you try installing a lightweight plugin such as cordova-plugin-echo or cordova-plugin-dialogs and get it working before you try to install this one. In case of problems it is easier to find help with the echo or dialog plugins.
