### ISSUE TITLE
SQLiteConnectorDatabase built in another package

### ISSUE THREAD

**Issue by Kaddath-R** [litehelpers/Cordova-sqlite-legacy#5]
Hi!

  Thanks a lot for your work! So i did choose this legacy version because as i read, this one supports Windows Phone and the widest support was one of the goal of my current project. Did various tests with different interfaces/structures, because i am currently testing different ways to do an hybrid app, always getting this issue.

  Actually it is not really an issue, but i found it rather unexpected: when i build the project for android and import it in eclipse, my project shows an error that prevents eclipse to run it. So i saw that 2 packages are created (io.liteglue and io.sqlc). In the first one, there is just one file "SQLiteConnectorDatabase.java". In the second, "SQLiteAndroidDatabase.java" and "SQLitePlugin.java".
  The problem is that the connector file is declared as belonging to the io.sqlc package while it is in io.liteglue one. Each time i import a project in eclipse (creating a new project each time and manually adding plugins), i have the same thing, and am obliged to move this file to the good package to get it to work.

  What is surprising though, now that i have installed ionic for testing, when i build the project from ionic command line (ionic run android) to install it straight on the phone, it works without any modification. If i try to import the project in eclispe, the error is still there!

  I was suspecting there is something related about the android connector (Android*sqlite-connector) mentionned in the readme (already read it several times, and searched for the same error). As i am still testing different solutions, installing this connector seemed a bit complex for now.

Maybe i didnt use this correcty, in case i am sorry :p 
Kaddath

**Comment by brodybits** [comment]
Hi @Kaddath-R,

You are right: in this version plugin.xml puts SQLiteConnectorDatabase.java in the wrong place. Eclipse is very sensitive to this while a lot of other tooling does not really seem to care.

I will fix this when I get a chance.

I am curious which versions of Windows Phone you want to support?

The standard Cordova-sqlite-storage as well as cordova-sqlite-ext support Windows Phone 8.1 as well as Windows 10 UWP (for desktop, laptop, tablet, *and* mobile). The WP8 version is based on a CSharp port of SQLite which is somewhat buggy and is out of date. I am hoping for an end of life for both WP8 and this version of the plugin to come soon.

**Comment by Kaddath-R** [comment]
Thanks a lot for the quick answer!

I have pretty bad knowledge of Windows Phone system versions, and had to assimilate a huge amount of info last month, learning cordova with different frameworks from almost zero. That's probably why i misunderstood WP support for the main plugin.

So it was a requisite from the nature of the app we want to develop that it has the widest support that can be possibly attainable, but for the moment WP 8.1 and Win 10 will be fairly enough, so i will switch to Cordova-sqlite-storage, and consider a different app version for WP8 later if needed.

Thanks again for the plugin and reactivity :)
Kaddath

**Comment by brodybits** [comment]
This version is now fixed. Thanks for reporting.
